---
- name: main
  hosts: overkill

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Create the `aur_builder` user
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
    
    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'

    - name: Install base-devel (needed for aur)
      community.general.pacman:
        name: base-devel
        update_cache: true

    - name: Installing AUR helper
      kewlfft.aur.aur:
        name: "{{ aur_helper }}"
      become: true
      become_user: aur_builder
    
    - name: Install AUR packages
      kewlfft.aur.aur:
        name: "{{ aur_packages }}"
        state: present
        use: "{{ aur_helper }}"
      become: true
      become_user: aur_builder
